[package]
name = "gpt-rs"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.71"
askama = "0.12.0"
async-openai = "0.10.3"
async-session = "3.0.0"
axum = {version = "0.6.18",  features = ["ws"]}
axum-sessions = "0.5.0"
csv = "1.2.1"
derive_builder = "0.12.0"
dhat = "0.3.2"
ndarray = "0.15.6"
rand = "0.8.5"
serde = {version = "1.0.163", features=["derive"]}
serde_json = "1.0.96"
tiktoken-rs = {version = "0.4.2", features=["async-openai"]}
tokio = {version = "1.28.1", features=["full"]}
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
tracing = "0.1.37"
tracing-subscriber = {version= "0.3.17", features = ["env-filter"]}


[profile.release]
debug = 1

[features]
dhat-heap = []    # if you are doing heap profiling
